# Snakemake config
input:
output: 'metamash.out/'
log: 'metamash/metamash.log'
threads: 1

# Snakemake Params
BigJobMem: 375000     
BigJobCpu: 80   
MediumJobMem: 32000
MediumJobCpu: 8     
SmallJobMem: 4000
SmallJobCpu: 1 

SmallTime: 5
BigTime: 300
MediumTime: 120

# mmseqs2 params
uniref50: 'uniref50'
gtdb_dir: '/hpcfs/users/a1667917/metagenomics_dbs/mmseqs2/GTDB'
tmp: '/hpcfs/users/a1667917/tmp'

# sourmash config 
sourmash:
  # The k-mer size(s) you'd like to use for profiling.
  ksize: [21, 31, 51]
  #ksize: 31
  # The relative or full path to the sourmash database file(s), for each
  # k-mer size you want to run. These can be downloaded from:
  # https://sourmash.readthedocs.io/en/latest/databases.html 
  # curl -JLO <url>
  search_databases:

    # estimatednumber of base pairs required for a database match.
    # note that this affects runtime and memory. We recommend running
    # with default threshold (50kb) first and then modifying if necessary.
    threshold_bp: 50000

    k21:
      - /Volumes/VERBATIM_HD_3/gtdb-rs214-reps.k21.zip

    k31:
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-archaea-k31.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-bacteria-k31.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-fungi-k31.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-protozoa-k31.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-viral-k31.zip
      - /Volumes/VERBATIM_HD_3/gtdb-rs214-reps.k31.zip
    k51:
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-archaea-k51.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-bacteria-k51.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-fungi-k51.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-protozoa-k51.zip
      #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-viral-k51.zip
      - /Volumes/VERBATIM_HD_3/gtdb-rs214-reps.k51.zip

  # The relative or full path to the corresponding lineage file(s) for
  # the sourmash databases specified above. Note that this file is not
  # different per k-mer size. Lineage files can be downloaded from:
  # https://sourmash.readthedocs.io/en/latest/databases.html 
  database_lineage_files:
    #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-archaea.lineages.csv.gz
    #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-bacteria.lineages.csv.gz
    #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-fungi.lineages.csv.gz
    #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-protozoa.lineages.csv.gz
    #- /hpcfs/users/a1667917/metagenomics_dbs/sourmash/genbank-2022.03-viral.lineages.csv.gz
    - /Volumes/VERBATIM_HD_3/gtdb-rs214.lineages.csv.gz
